### ISSUE TITLE
libsense.so in x64

### ISSUE THREAD

**Issue by argraur** [denysvitali/magisk-pixel2-features#2]
```10-19 17:29:30.432   773  2925 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.google.intelligence.sense/.ambientmusic.AmbientMusicSetupWizardActivity} from uid 0
10-19 17:29:30.478   773  2899 I ActivityManager: Start proc 6918:com.google.intelligence.sense/u0a84 for activity com.google.intelligence.sense/.ambientmusic.AmbientMusicSetupWizardActivity
10-19 17:29:30.641   773  3145 I OpenGLRenderer: Initialized EGL, version 1.4
10-19 17:29:30.641   773  3145 D OpenGLRenderer: Swap behavior 2
10-19 17:29:30.791  6918  6918 D AndroidRuntime: Shutting down VM
10-19 17:29:30.792  6918  6918 E AndroidRuntime: FATAL EXCEPTION: main
10-19 17:29:30.792  6918  6918 E AndroidRuntime: Process: com.google.intelligence.sense, PID: 6918
10-19 17:29:30.792  6918  6918 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/priv-app/AmbientSensePrebuilt/AmbientSensePrebuilt.apk"],nativeLibraryDirectories=[/system/priv-app/AmbientSensePrebuilt/lib/arm64, /system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]] couldn't find "libsense.so"
10-19 17:29:30.792  6918  6918 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
10-19 17:29:30.792  6918  6918 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1657)
10-19 17:29:30.792  6918  6918 E AndroidRuntime:        at com.google.intelligence.sense.SenseApplication.<clinit>(Unknown Source:2)
10-19 17:29:30.792  6918  6918 E AndroidRuntime:        at java.lang.Class.newInstance(Native Method)
10-19 17:29:30.792  6918  6918 E AndroidRuntime:        at android.app.Instrumentation.newApplication(Instrumentation.java:1101)
10-19 17:29:30.792  6918  6918 E AndroidRuntime:        at android.app.Instrumentation.newApplication(Instrumentation.java:1086)
10-19 17:29:30.792  6918  6918 E AndroidRuntime:        at android.app.LoadedApk.makeApplication(LoadedApk.java:965)
10-19 17:29:30.792  6918  6918 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5765)
10-19 17:29:30.792  6918  6918 E AndroidRuntime:        at android.app.ActivityThread.-wrap1(Unknown Source:0)
10-19 17:29:30.792  6918  6918 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
10-19 17:29:30.792  6918  6918 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:105)
10-19 17:29:30.792  6918  6918 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
10-19 17:29:30.792  6918  6918 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6541)
10-19 17:29:30.792  6918  6918 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-19 17:29:30.792  6918  6918 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
10-19 17:29:30.792  6918  6918 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
10-19 17:29:30.805   773  2899 W ActivityManager:   Force finishing activity com.google.intelligence.sense/.ambientmusic.AmbientMusicSetupWizardActivity
10-19 17:29:30.813   773   800 I ActivityManager: Showing crash dialog for package com.google.intelligence.sense u0```

**Comment by argraur** [comment]
AmbientSense looks for libsense.so in */lib64 folders, so it means that libsense.so should be in x64 too.

**Comment by argraur** [comment]
@denysvitali what device do you own?

**Comment by denysvitali** [comment]
N6P (arm64) and Pixel C (arm64). In my case, when the libsense.so file is placed in /system/lib/ the package doesn't complain (doesn't throw any error like yours do).

I'm running Android O, w/ September security patches on both devices

**Comment by argraur** [comment]
I'm running Android O, w/ October patch on Nexus 5X :/

**Comment by denysvitali** [comment]
Don't worry. We can create a symlink :)

**Comment by argraur** [comment]
Symlink from /system/lib/libsense.so? Does not work.

**Comment by denysvitali** [comment]
Why not? Should we really copy it?

**Comment by argraur** [comment]
You can't copy x86 library to lib64 huh I tried already

**Comment by denysvitali** [comment]
Is it arm? I thought it was arm64... I gotta check as soon as I'm back at my notebook

**Comment by denysvitali** [comment]
Just checked from my phone: you are right. It's a 32 bit library (damn!)

`libsense.so: ELF shared object, 32-bit LSB arm, dynamic (/system/bi
/linker), BuildID=8ca0677f140a75815ed4fc805a0ee0c3, stripped`

**Comment by denysvitali** [comment]
I can't seem to find the x64 version anywhere. I just copied it to `/system/lib64/` as a (bad) workaround.  
  
Btw, I just noticed this:
```
AmbientSensePrebuilt/AmbientSensePrebuilt/AndroidManifest.xml:<?xml version="1.0" encoding="utf-8" standalone="no"?><manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.google.intelligence.sense" platformBuildVersionCode="26" platformBuildVersionName="8.0.0">
PixelAmbientServices/PixelAmbientServices/AndroidManifest.xml:<?xml version="1.0" encoding="utf-8" standalone="no"?><manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.google.intelligence.sense" platformBuildVersionCode="27" platformBuildVersionName="8.1.0">
```
I've got two versions of the com.google.intelligence.sense (one is called AmbientSense and the other PixelAmbientSense). One targets 8.0.0, the other targets 8.1.0

**Comment by argraur** [comment]
You should not put both into system because they still have conflicting package names

**Comment by argraur** [comment]
Only AmbientSensePrebuilt

**Comment by Ramisky** [comment]
I think I can help got an idea

**Comment by Ramisky** [comment]
I think we should check both on the pixel

**Comment by Ramisky** [comment]
And for the libsense.so x64 why not get it from a pixel 2?
